### ISSUE TITLE
Small issue in ReadMe example code

### ISSUE THREAD

**Issue by jrgibson** [robbyklein/utility-uss#1]
This is a tiny thing, but in your ReadMe file, your example code doesn't close the Label, so UI Toolkit complains.

Thank you for making this. I look forward to using it!

  – Jeremy

**Comment by robbyklein** [comment]
> This is a tiny thing, but in your ReadMe file, your example code doesn't close the Label, so UI Toolkit complains.
> 
> Thank you for making this. I look forward to using it!
> 
> – Jeremy

Good catch, just updated the readme. Thanks!
